services:
  - type: web
    name: quiz-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn quiz_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: quiz_project.settings
      - key: PYTHON_VERSION
        value: 3.11
