services:
  - type: web
    name: vishesh-quiz-project
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python manage.py migrate &&
      gunicorn quiz_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: quiz_project.settings
      - key: PYTHON_VERSION
        value: 3.10
