services:
  - type: web
    name: vishesh-quiz-project
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn quiz_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
